### ISSUE TITLE
Error SteamworksAuthFail - can't sign in with mod installed

### ISSUE THREAD

**Issue by dchow1992** [slushiegoose/Town-Of-Us#103]
I'm unable to sign in since updating my game to 2021.4.12,
I can sign in if I launch normally through steam, but not while using the mod.

**Comment by dchow1992** [comment]
if anyone else runs into this issue, 
I solved it for myself by running among us as administrator. that allowed me to sign in

**Comment by kevinkid135** [comment]
Running as admin did not work for me.
Instead I started among us normally through steam, logged in, closed among us, and ran the modded among us.
