### ISSUE TITLE
Mode is not loading

### ISSUE THREAD

**Issue by stofinkapitoma** [slushiegoose/Town-Of-Us#11]
Hello, I downloaded your mode with my friends and I have one issue. When my friends launch that mode they can see this: 
![image](https://user-images.githubusercontent.com/79771712/109402826-444ed780-7959-11eb-8e9b-b5f4df825c3c.png) .

unfortunately I see only that v2020.12.9s. They were helping me through the discord so I shouldnt make any mistake during instalation becuase  I proceeded same as them and they can play without problems... Do u know any settings (or something else) in computer that could cause this error?

Thanks for the answer!

**Comment by Black-Dragon131** [comment]
Hey stofinkapitoma,
try it with this mod manager. It will install the mod automatically:
https://aumm.black-dragon131.de/

**Comment by Woodi-dev** [comment]
You might be missing some x86 c++ libs. Pls try to install:
https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by dosentaste** [comment]
Wooodi-dev, i have tryed your suggestion but it doesnt work for me. when i open it it still just opens regular among us

**Comment by stofinkapitoma** [comment]
> Wooodi-dev, i have tryed your suggestion but it doesnt work for me. when i open it it still just opens regular among us

One guy on disco https://aka.ms/vs/16/release/vc_redist.x86.exe

> You might be missing some x86 c++ libs. Pls try to install:
> https://aka.ms/vs/16/release/vc_redist.x86.exe

It worked.. Thanks a lot :O :D
