### ISSUE TITLE
Mod doesn't work in the newest update of the game v2021.5.10s

### ISSUE THREAD

**Issue by dz10p4** [slushiegoose/Town-Of-Us#141]

**Comment by jshwhitlow** [comment]
Second this. Discovered this today with friends, in addition the "kill" button for the imposter won't work if this is installed, so it doesn't just not work, it also breaks the game.

**Comment by PokiUno** [comment]
Ditto, I typically play modded w/ a few friends and I re did all of the process's needed for installation, it just doesn't work with Among Us.  :/

**Comment by KyaniteKirin** [comment]
Kind of expected, but can confirm that the mod does not currently function with the new among us update.

**Comment by Hanewmon** [comment]
Tried to play with friend and did not work can confirm.

**Comment by dz10p4** [comment]
if anyone wants to play the mod before it gets updated, here is a link to the zipped installation [](https://mega.nz/file/QqRwxBhR#Y6Dsu8ik0SbvorLgtAd9PitWBsiIWb3cCBmqo3kAKUw)

**Comment by irish-queen** [comment]
How did you guys get it to work again? Mine just won't work and disables the kill button

**Comment by KyaniteKirin** [comment]
> How did you guys get it to work again? Mine just won't work and disables the kill button

You need to access your among us folder itself, and you need to delete everything in it. Then uninstall the game. Reinstall the game. Simply uninstalling the game without deleting the files will not fix the problem. 

If you want town of us reinstalled, follow the installation steps :) basically extract the zip to the among us folder
