### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by Maryjane007** [slushiegoose/Town-Of-Us#150]
When will you release the version of TownOfUs with the assassin and the undertaker and the other dudes?

**Comment by MandyMeindersma** [comment]
The new roles are currently only for beta testers meaning patreon supporters, streamers and members of the staff team have access to it, the rest is gonna have to wait until the update is ready for public release.

**Comment by Maryjane007** [comment]
Ok, thanks for the info!
