### ISSUE TITLE
Imp roles do not work in freeplay

### ISSUE THREAD

**Issue by RedstoneBoy0509** [slushiegoose/Town-Of-Us#153]
### Seriously?
I was playing with ToU for the first time and tried out Time Lord and Arsonist in freeplay. I later tried to test out Miner in freeplay and just became a crewmate? Can someone please help?

**Comment by TwilightZebby** [comment]
@RedstoneBoy0509 This mod doesn't work for Freeplay mode, as stated in the #known-issues channel on the ToU Discord, Freeplay mode works differently to other modes on Among Us

**Comment by RedstoneBoy0509** [comment]
Ok, but the Time Lord did work
