### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by Bublelift** [slushiegoose/Town-Of-Us#155]
Hello,
don't know why but after the mod installation I was laving lag spikes every 3 seconds. This made playing the game very annoying so I decided to remove mod files. After this, the game came back to be perfectly fluent. I don't really know if this happened only to me, just leaving this so you can track the issue.

**Comment by balloplayz** [comment]
you have bad pc if you lagg alot
 sorry to say but get new pc or laptop

**Comment by Bublelift** [comment]
yeah sorry didnt know gtx1060 6gb and i76700 with 16gb ram is so lame it cant run your code ;(((((
sorry for bothering

**Comment by Bublelift** [comment]
Alright folks, if you have similar issue make sure to open your NVIDIA Control Panel, go to _Adjust image setting with preview_ in the _3D Settings_ category and check the _Let the 3D application decide_ option as marked. Then go to your Among Us graphics settings and make sure you have V-sync turned on. This allowed me to have a nice fluent gameplay, because my GPU seetings were focused on efficiency and the card was pumping FPS like crazy, so that there were too much of them for fluent gameplay. Also eat ass balloplayz.
