### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by manniL** [slushiegoose/Town-Of-Us#16]
Hey 👋 

Is there any reason why the source code isn't included in the repo but only in the releases (though serving it under the GPL license)?

Similar issues: #21 #20

**Comment by soerface** [comment]
The sourcecode isn't included on the releases page either, is it? @slushiegoose you are using other mods which are licensed under the GPL, therefore you are obliged to release your sources, too. You are furthermore using for example the Couple Mod which @Woodi-dev gave the license CC BY-ND 4.0, so you aren't even allowed to publish derivates of it if you didn't talked to Woodi-dev before.

**Comment by Woodi-dev** [comment]
@soerface No worries. He asked me and I gave him permission. I am not a selfish guy. He did a good job.

**Comment by MatzeHpunkt** [comment]
Then he should publish his code right??

**Comment by zokradonh** [comment]
If he spoke with the other authors they may have grant him a license different from the license that is publicly available to everyone on GitHub.

So as long as you are not an author who's rights are compromised you should not force something here.

**Comment by manniL** [comment]
> 
> 
> If he spoke with the other authors they may have granted him a license different from the license that is publicly available to everyone on GitHub.
> 
> So as long as you are not an author who's rights are compromised you should not force something here.

So also the Authors from Reactor and BepInEx (and I doubt the latter one though). Plus, the mod itself is released under GPL as well.

**Comment by DorCoMaNdO** [comment]
Reactor, BepInEx are LGPL, regardless you can't really dual license GPL code, every contributor contains rights, you'd need all the contributors from all the mods he used to agree, that's not happening.

**Comment by zokradonh** [comment]
> Reactor, BepInEx are LGPL, regardless you can't really dual license GPL code, every contributor has rights, you'd need all the contributors from all the mods he used to agree, that's not happening.

Yes, you are right. In fact, there are a lot of license problems out there on several repositories.

So let's just ask the author nicely for source code, so that we can contribute and learn.

**Comment by slushiegoose** [comment]
Uploaded!
