### ISSUE TITLE
Assasin And Undertaker Issue

### ISSUE THREAD

**Issue by FeateyFan** [slushiegoose/Town-Of-Us#162]
When I load Among Us Town Of Us, the Assasin and Undertaker role won't appear. Please help me.

**Comment by balloplayz** [comment]
only beta testers get the roles and streamers and workers of staff sorry to say

**Comment by FeateyFan** [comment]
Thank you, I already found out how to play it in the beta in 2.1.0-dev. I appreciate your help.
