### ISSUE TITLE
link to town of us beta  2.1.0

### ISSUE THREAD

**Issue by balloplayz** [slushiegoose/Town-Of-Us#169]
https://www.mediafire.com/file/s1fkjoezqaoqkjr/Among-Us_Beta.zip/file

**Comment by ineverusegithub** [comment]
![Capture](https://user-images.githubusercontent.com/83991389/120586473-77858480-c3e8-11eb-9ad4-70dad9e0b2ea.PNG)
It got flagged for a virus

**Comment by balloplayz** [comment]
dont know what to tell you your pc is way to protective

**Comment by jcoffm** [comment]
> ![Capture](https://user-images.githubusercontent.com/83991389/120586473-77858480-c3e8-11eb-9ad4-70dad9e0b2ea.PNG)
> It got flagged for a virus

That's not a PC, that's VirusTotal, and as a general rule, if only one engine flags a file on VirusTotal, it is in virtually all cases a false positive.
