### ISSUE TITLE
About Updates

### ISSUE THREAD

**Issue by aleynia** [slushiegoose/Town-Of-Us#30]
is anyone aware of when the mod creator / devs will be updating it, to fit the new Among Us update ? no rush at all, just wondering, because i keep checking. it'd be easier to know when, so i can have some sort of schedule or something, i guess.

**Comment by Dgoat724236** [comment]
they are in the process of updating it, and right now its in a beta accessible to streamers. theyre posting updates on [their discord server](https://discord.gg/bYSaT74KzT), in case youre interested
![image](https://user-images.githubusercontent.com/65834932/110876895-07aaa680-829e-11eb-858a-aeffa318a964.png)

**Comment by aleynia** [comment]
i appreciate the answer !
