### ISSUE TITLE
zip packaging

### ISSUE THREAD

**Issue by Black-Dragon131** [slushiegoose/Town-Of-Us#4]
Hello,

would it be poossible to pack the release zip without the top folder "Town Of Us"?
My Among Us Mod Manager installs mods directly from github releases and all other mods just contain the files without this top folder. I would like to include your mod to AUMM if you could change that.
You can find AUMM here: https://aumm.black-dragon131.de/

**Comment by moritzruth** [comment]
I literally created the same tool with the exact same name :joy:

**Comment by moritzruth** [comment]
FYI: This is changed in the latest version.

**Comment by slushiegoose** [comment]
^
