### ISSUE TITLE
Source code of 1.1.0

### ISSUE THREAD

**Issue by Snowad14** [slushiegoose/Town-Of-Us#43]
You only gave the source code of version 1.0.3, I don't know if this is done on purpose but I would love it with the new source code

**Comment by NamesAreAPain** [comment]
I don't understand why this is so common in the Among Us modding community in general. What's the point in putting an open source license on your code that you have no intention of actually posting the source too?

**Comment by slushiegoose** [comment]
Yeah that was me being dumb - uploaded now!
