### ISSUE TITLE
I can't figure out how to download it

### ISSUE THREAD

**Issue by ChargedCM** [slushiegoose/Town-Of-Us#54]
every time i follow the steps it doesnt work. Or is it because of the new update? If so, I need to know how to go back versions.

**Comment by Olive-Branches** [comment]
You might be missing some x86 c++ libs. Pls try to install:
https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by ChargedCM** [comment]
thank you so much now I can upload good youtube videos!

**Comment by slushiegoose** [comment]
Glad you sorted it out!
