### ISSUE TITLE
Game not finished when Janitor

### ISSUE THREAD

**Issue by MatuxGG** [slushiegoose/Town-Of-Us#6]
Hello,

First of all, your mod is awesome. It works really well and today's fix were really good.

When there is only the Janitor left, the game is not finished. Is it normal ?

Thanks and once again, nice job :)

**Comment by N47h** [comment]
the janitor could still win without killing anyone, if they're good

**Comment by MatuxGG** [comment]
Oh ok then !

Thanks for your answer.
