### ISSUE TITLE
kinda big issue (at least for me)

### ISSUE THREAD

**Issue by notAari** [slushiegoose/Town-Of-Us#88]
i cant create a lobby, join a lobby or go in freeplay after i put the files in the among us folder help qwp

**Comment by GithubMod-JustHereToDownload** [comment]
Mine never worked because of the BETA and version problems, but from past experience, I recommend deleting the file then redownloading it or redownload Among Us. This might not work but I'd try this personally.

**Comment by Alex10903** [comment]
Thank you!   
  
  
  
  
  
    
  

  
  
>

**Comment by notAari** [comment]
nope didnt work
