### ISSUE TITLE
Stuck after meeting

### ISSUE THREAD

**Issue by Lissam54** [slushiegoose/Town-Of-Us#90]
Hello, as related in the title, all players are stuck around the meeting table after a meeting. 

Here is our configuration :
- amoung us version :
    - Build ID : 6472679
    - Date of maj : 1st april 2021 at 11:02
- town of us version : 
    - 2.0.0 from your github
    - date of download : 11 april 2021 at 00:30

Could you please fix it ? Many thanks !
    
Thanks for providing and maintain this awesome compilation of mods ;)

**Comment by sambrodriguez** [comment]
We've been having this issue too, if you click the settings button in the top right it seems to fix it (each player has to do it individually).

**Comment by Orionzip** [comment]
This is an issue in the normal game, too. The only solution seems to be what @sambrodriguez said above, going to settings and then going back out.

**Comment by Lissam54** [comment]
Ok thanks, i close my issue then.
