### ISSUE TITLE
README error

### ISSUE THREAD

**Issue by s-kyy** [slushiegoose/Town-Of-Us#95]
For step 7 in the installation instructions you wrote:
> 7. Locate the downloaded .zip file, and move it to the `Town of Us` folder.
Usually, this can be found in the Downloads folder.

Did you mean this instead?
7. Locate the downloaded .zip file, and move it to the `Among Us` folder.
Usually, the `.zip` file can be found in the Downloads folder.

**Comment by gallagherrchris** [comment]
Step 1 of the instructions are to create a new `Town of Us` folder.  The steps are to refresh your among us install (make sure it is clean), then copy everything into this new folder.  This is especially helpful for new people so they realize they're running the mod and not the original game.

**Comment by s-kyy** [comment]
@gallagherrchris My bad! I was going off based on the previous instructions, so I got confused.
